services:
  - type: web
    name: practica-react-server
    env: node
    plan: free
    rootDir: .
    buildCommand: corepack enable pnpm && pnpm install && cd react-app/server && pnpm run build
    startCommand: cd react-app/server && pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_POOLING
        sync: false
      - key: ACCEPTED_ORIGINS
        sync: false
